### ISSUE TITLE
Incompatibility with Lord of the Rings: Renewed

### ISSUE THREAD

**Issue by SiliconAshes** [Unixkitty/timecontrol#5]
After using Extended Days in 1.12.2, I went looking for similar capability in 1.16.5, and found Time Control.  Thank you very much for writing this.  I like it a lot.

I have found an incompatibility bug with the Lord of the Rings: Renewed Mod.  I have not seen this mentioned before, and apologize if it has been.  With this mod installed, the day-night cycle does not progress in "Middle Earth".  I have only tested this in a normal single player game where one spawns in the standard overworld, and uses a portal to go to Middle Earth.

Steps to reproduce the bug:

1. Using a clean 1.16.5 Minecraft instance, install Forge - I tested with Forge 36.2.4
2. Install Lord of the Rings: Renewed (4.7) and Time control (1.16.5-1.1.2.0)
3. Start a new world.
4. Create a portal (toss an LOTR Gold Ring into a source block of lava)
5. Go through the portal to Middle Earth - The sun does not move.  It does when Time Control is not installed.

I would also submit this to the LOTR: Renewed bug tracker since it is quite likely their bug, but they use Discord, and I... do not.

**Comment by Unixkitty** [comment]
After 1.12.2 I made my mod only directly affect Overworld's time, and normally dimensions that have a daylight cycle copy Overworld's time, which is expected behaviour.

The issue you're facing is that LOTR: Renewed doesn't seem to be copying Overworld's time, but instead implementing it's own cycle that lasts 48000 ticks.
